project:
  type: website
  output-dir: docs

website:
  title: "Tong Wu"
  navbar:
    background: "#536878"
    left:
      - href: publications.qmd
        text: Publications
      - href: tools.qmd
        text: Software & Database
  page-footer:
    left: "© 2023 personal website. Powered by <a href='https://quarto.org/'>Quarto</a>."
    right:
      - icon: github
        href: https://github.com/wyc9559
      - icon: twitter
        href: https://twitter.com/Tongwu9559
    background: "#536878"

format:
  html:
    theme: cosmo
    toc: true
